spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nk_dev?useunicode=true&characterencoding=utf-8
    username : naamk
    password: naamk_password
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 6
      max-lifetime: 240000
      maximum-pool-size: 200
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        default_schema: naamk_bank
#      '[hibernate.default_batch_fetch_size]' : 100

logging:
  level:
    '[kr.co.naamk]': INFO