=== Create Common Group Code `( 공통 그룹 코드 생성 )`
이 API는 공통 그룹 코드를 생성하는 기능을 제공합니다.

[NOTE]
====
- 공통 그룹 코드(cmmnGrpCd)은 중복이 허용되지 않습니다.
====
operation::cmmn-controller-test/create-cmmn-grp[snippets="curl-request,request-fields,http-request"]
operation::cmmn-controller-test/create-cmmn-grp[snippets="response-fields,http-response"]


=== Update Common Group Code `( 공통 그룹 코드 수정 )`
이 API는 공통 그룹 코드를 수정하는 기능을 제공합니다.

[NOTE]
====
- 공통 그룹 코드(cmmnGrpCd)의 수정이 불가합니다.
- 응답의 Response field의 body의 데이터는 비어있습니다.
====
operation::cmmn-controller-test/update-cmmn-grp[snippets="curl-request,path-parameters,request-fields,http-request"]
operation::cmmn-controller-test/update-cmmn-grp[snippets="response-fields,http-response"]


=== Delete Common Group Code `( 공통 그룹 코드 삭제 )`
이 API는 공통 그룹 코드를 삭제 기능을 제공합니다.

[NOTE]
====
- 공통 그룹 코드(cmmnGrpCd)삭제 시, 해당 공통 코드를 Fk로 가진 공통 코드 또한 삭제됩니다.
- 응답의 Response field의 body의 데이터는 비어있습니다.
====
operation::cmmn-controller-test/delete-cmmn-grp[snippets="curl-request,path-parameters,http-request"]
operation::cmmn-controller-test/delete-cmmn-grp[snippets="response-fields,http-response"]


=== Get All Common Group Code `( 공통 그룹 코드 전체 조회 )`
이 API는 공통 그룹 코드 전체 조회 기능을 제공합니다.

[NOTE]
====
- 전체 데이터를 조회하는 기능을 제공합니다.(limit X, pagination X)
- 정렬 기준 X
====
operation::cmmn-controller-test/get-all-cmmn-grps[snippets="curl-request,http-request"]
operation::cmmn-controller-test/get-all-cmmn-grps[snippets="response-fields,http-response"]


=== Get Detail Common Group Code `( 공통 그룹 코드 상세 조회 )`
이 API는 공통 그룹 코드 상세 조회 기능을 제공합니다.

[NOTE]
====
- 단일 데이터 조회입니다.
====
operation::cmmn-controller-test/get-detail-cmmn-grp[snippets="curl-request,path-parameters,http-request"]
operation::cmmn-controller-test/get-detail-cmmn-grp[snippets="response-fields,http-response"]


=== Create Common Code `( 공통 코드 생성 )`
이 API는 공통 코드 생성 기능을 제공합니다.

[NOTE]
====
- 공통 그룹 코드 내에 속하는 코드를 생성으로, 파라미터로 공통그룹 id를 넘깁니다.
- 응답의 Response field의 body의 데이터는 비어있습니다.
====
operation::cmmn-controller-test/create-cmmn[snippets="curl-request,path-parameters,request-fields,http-request"]
operation::cmmn-controller-test/create-cmmn[snippets="response-fields,http-response"]


=== Update Common Code `( 공통 코드 수정 )`
이 API는 공통 코드 수정 기능을 제공합니다.

[NOTE]
====
- 그룹 내의 겹치는 코드값(cmmnCd)가 중복이 되지 않도록 수정이 가능합니다.
- 응답의 Response field의 body의 데이터는 비어있습니다.
====
operation::cmmn-controller-test/update-cmmn[snippets="curl-request,path-parameters,request-fields,http-request"]
operation::cmmn-controller-test/update-cmmn[snippets="response-fields,http-response"]


=== Delete Common Code `( 공통 코드 삭제 )`
이 API는 공통 코드 삭제 기능을 제공합니다.

[NOTE]
====
- 응답의 Response field의 body의 데이터는 비어있습니다.
====
operation::cmmn-controller-test/delete-cmmn[snippets="curl-request,path-parameters,http-request"]
operation::cmmn-controller-test/delete-cmmn[snippets="response-fields,http-response"]


=== Get All Common Code In Group`( 그룹 내 공통 코드 전체 조회 )`
이 API는 특정 공통 그룹 내의 공통 코드 전체 조회 기능을 제공합니다.

[NOTE]
====
- 공통 그룹 코드 내에 속하는 코드 조회므로, 파라미터로 공통그룹 id를 넘깁니다.
- 응답의 Response field의 body의 데이터는 정렬번호(orderNum)을 기준으로 정렬되었습니다.
====
operation::cmmn-controller-test/get-all-cmm-by-cmmn-grp-id[snippets="curl-request,path-parameters,http-request"]
operation::cmmn-controller-test/get-all-cmm-by-cmmn-grp-id[snippets="response-fields,http-response"]


=== Get Detail Common Code In Group`( 그룹 내 공통 코드 상세 조회 )`
이 API는 특정 공통 그룹 내의 공통 코드 상세 조회 기능을 제공합니다.

[NOTE]
====
- 단일 데이터 조회입니다.
- 공통 그룹 코드 내에 속하는 코드 조회므로, 파라미터로 공통그룹 id를 넘깁니다.
====
operation::cmmn-controller-test/get-detail-cmmn-in-cmmn-grp[snippets="curl-request,path-parameters,http-request"]
operation::cmmn-controller-test/get-detail-cmmn-in-cmmn-grp[snippets="response-fields,http-response"]


=== Get Detail Common Code `( 공통 코드 상세 조회 )`
이 API는 공통 코드 상세 조회 기능을 제공합니다.

[NOTE]
====
- 단일 데이터 조회입니다.
- 그룹 코드와 상관없는 공통 코드 상세 조회합니다.
====
operation::cmmn-controller-test/get-detail-cmmn[snippets="curl-request,path-parameters,http-request"]
operation::cmmn-controller-test/get-detail-cmmn[snippets="response-fields,http-response"]
