spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ENC(TYbWONRpnK+eUGe+DGNB0ukuV5EvhAqhFqF+BQOesiB0LKWmPsE9VvofDhosDrceTEVfufigtoEbnDywF3QMWHVjy5h6TvlKsTPKUJIlrMRnRTyTANSXiFQMokbtgdQXZaF+MgIo/G46TdLKaqTO/w==)
    username : ENC(BzQK0/38GkerJgfs8ILakyvTbKznpHwQyMzR12UDHvCMSMhjPerCR7pociI/5MGb)
    password: ENC(lnsSMnBSRJNSUisnaVVMLNov5Au5cJw2oQCsllyqErQMTDWSqIZIEjAVxTQ3MFWs)
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 6
      max-lifetime: 240000
      maximum-pool-size: 200
    auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      '[hibernate.default_batch_fetch_size]' : 100

logging:
  level:
    '[kr.co.naamkbank]': INFO