spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ENC(o441akJTqhKfFqit/yMccXsQow5jamewlWPwPPZb80Gf1l12l65Eu+QTk0Ah54ZTb8SRLQSfMoL38ssezun+U74YLeQAAE59xBk2UWdYb+77qX4+XJrewfeEAHs//43XbssruhC0XNK+5kTXB4a+SA==)
    username : ENC(BzQK0/38GkerJgfs8ILakyvTbKznpHwQyMzR12UDHvCMSMhjPerCR7pociI/5MGb)
    password: ENC(lnsSMnBSRJNSUisnaVVMLNov5Au5cJw2oQCsllyqErQMTDWSqIZIEjAVxTQ3MFWs)
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 6
      max-lifetime: 240000
      maximum-pool-size: 200
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        default_schema: ENC(H18FCFxj8pzuepzje8VCYCEFnxzHKUa6F7vDH1RPVwAipy9ef+YuRyfnafX4yEUP)
#      '[hibernate.default_batch_fetch_size]' : 100

logging:
  level:
    '[kr.co.naamk]': INFO