spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL
    username : naamk
    password: naamk_password
  # 초기 필요 schema, data load
  sql:
    init:
      mode: never
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  hikari:
    connection-timeout: 3000
    validation-timeout: 3000
    minimum-idle: 6
    max-lifetime: 240000
    maximum-pool-size: 200
  auto-commit: false
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      '[hibernate.default_batch_fetch_size]' : 100
      '[hibernate.format_sql]': true
    show-sql: true
    output:
      ansi:
        enabled: always

logging:
  level:
    '[kr.co.naamkbank]': DEBUG
    '[org.hibernate.type]': TRACE